### ISSUE TITLE
CFR section number tracking issue

### ISSUE THREAD

**Issue by divergentdave** [unitedstates/citation#117]
I put together a [test harness](https://gist.github.com/divergentdave/df9d3dcebe1f571a1d11) that reads through an eCFR bulk data zip file, pieces together a citation for each section represented in the XML files, and tries running it through `Citation.find`. This issue is for tracking all the problems this harness exposes.

- [ ] Not catching final letter for 12 CFR § 226.5a or 10 CFR § 205.192A
- [ ] Doesn't handle letter, hyphen, and number at the end of a section number (17 CFR § 240.10b-21)
- [ ] Can't handle range of sections (i.e. 12 CFR §§ 3.4-3.9)
- [ ] Doesn't recognize letters in part numbers (i.e. 12 CFR § 708a.101)
- [ ] More than one hyphen in the section number (i.e. 10 CFR § 960.3-1-1, 10 CFR § 960.3-1-4-1, and 48 CFR 970.3102-05-30-70)
- [ ] Letter in parentheses, hyphen, and number (i.e. 26 CFR § 1.1031(a)-1)
- [ ] Letter in parentheses, hyphen, number, and capital T (26 CFR § 1.1031(d)-1T)
- [ ] Hyphen in part number (41 CFR § 128-1.5004)
- [ ] Hyphen in part number, hyphen in section number (41 CFR § 128-48.001-50)
- [ ] Capital T in the middle of a section number, plus a hyphen later on (33 CFR § 100.35T01-0125 and 33 CFR § 100.T07-0110)
- [ ] Hyphens and capital letters in the middle of a section number (48 CFR 53.303-DD-254, 48 CFR 53.303-DD-441, 48 CFR 53.303-WH-347)
- [ ] Hyphen in a section number and a capital letter at the end (48 CFR 53.302-1419A)
- [ ] 17 CFR § 210.6A-01
- [ ] 26 CFR § 1.1402(e)-1A
- [ ] 12 CFR § 563d.3b-6

There are also a few issues in the eCFR itself, such as an &amp;sect; that was missing an ampersand. I'll gather these up, double-check them against the live site, and send them to ecfr@nara.gov. (per the [FAQs](http://www.ecfr.gov/cgi-bin/ECFR?SID=5bb3df1c811d4c1e4e2f362eeb70e59f&mc=true&page=faq#quest11))

**Comment by divergentdave** [comment]
I updated the list above with more samples, this should provide a good cross-section of the patterns seen in practice.

**Comment by konklone** [comment]
Very very nice! Are these all fixable with More Regex?

**Comment by divergentdave** [comment]
By and large yes, but we'll need to lift some logic from other parsers to
handle ranges.

**Comment by divergentdave** [comment]
I finally remembered to email NARA about the "sect;" issue, and I got a lovely reply back. In a mere two days that they had fixed the issue, they had fixed the same thing in eight other places, and they are now going to make improvements to their tools to better handle other SGML/XML character entity typos!
